window.ELIXIR_CATALOG = {
  "source": {
    "name": "Perfumes_Recommender final_df.csv",
    "repository": "https://github.com/rawanalqarni/Perfumes_Recommender",
    "originalDataSource": "GoldenScent scraped dataset described by the source repository",
    "notes": "Curated subset generated for Elixir Grove practice storefront; prices are in SAR."
  },
  "products": [
    {
      "id": "eg-001-roberto-cavalli-paradiso",
      "name": "Roberto Cavalli Paradiso",
      "brand": "Roberto Cavalli",
      "gender": "Women",
      "family": "Woody",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2015,
      "priceSar": 169,
      "rating": 4.95,
      "ratingCount": 17,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3607347733423c-roberto-cavalli-paradiso---75-ml.jpg",
      "description": "Woody floral fragrance, a subtle aroma that makes you feel fresh with a stunning blend of citrus, jasmine, and cypress.",
      "notes": [
        "bergamot",
        "citruses",
        "cypress",
        "jasmine",
        "mandarin",
        "parasol pine",
        "pink laurel"
      ],
      "ingredients": "citrus, mandarin, bergamot, jasmine, pine, cypress, laurel."
    },
    {
      "id": "eg-002-mancera-roses-vanille",
      "name": "Mancera Roses Vanille",
      "brand": "Mancera",
      "gender": "Women",
      "family": "Floral",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "120 ml",
      "year": 2017,
      "priceSar": 409,
      "rating": 4.93,
      "ratingCount": 18,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/mancera_roses_vanille_3_1.jpg",
      "description": "The perfumer Pierre Mancera presents Roses Vanille which hits you first with notes of fresh lemon of calabria and then sneaks on you with turkish delight and rose with the base notes of...",
      "notes": [
        "cedarwood",
        "fresh lemon of calabria",
        "intense vanilla & white musk",
        "rose",
        "turkish delight"
      ],
      "ingredients": "fresh lemon of calabria, turkish delight with rose, cedarwood, intense vanilla & white musk"
    },
    {
      "id": "eg-003-roberto-cavalli-roberto-cavalli",
      "name": "Roberto Cavalli \"Roberto Cavalli\"",
      "brand": "Roberto Cavalli",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2012,
      "priceSar": 129,
      "rating": 5.0,
      "ratingCount": 7,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/r/o/roberto_cavalli_roberto_cavalli_her_eau_de_parfum_1.jpg",
      "description": "An oriental floral fragrance for women that gives you great comfort, energy, and love for life thanks to its amazing ingredients with a mixture of pink pepper, African orange blossom, and...",
      "notes": [
        "african orange flower",
        "benzoin",
        "pink pepper",
        "tonka bean",
        "vanilla"
      ],
      "ingredients": "pink pepper, african orange flower, benzoin, tonka bean, vanilla."
    },
    {
      "id": "eg-004-dolce-gabanna-l-imperatrice-3-pour-femme",
      "name": "Dolce & Gabanna L'imperatrice 3 Pour Femme",
      "brand": "Dolce&Gabbana",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2009,
      "priceSar": 199,
      "rating": 5.0,
      "ratingCount": 6,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/4/3423473020615-dolce-_-gabbana-l_imperatrice-01_1_.png",
      "description": "Perfume for the energetic woman who is a hero in her movie in life every day! It keeps you vibrant and sparkling with irresistible attractiveness, a combination of kiwi, lemon and...",
      "notes": [
        "cyclamen",
        "jasmine",
        "kiwi",
        "lemon trees",
        "musk",
        "pink pepper",
        "rhubarb",
        "sandalwood",
        "watermelon"
      ],
      "ingredients": "watermerlon, kiwi, pink cyclamen, musk, pink pepper, jasmine, sandalwood, lemon tree"
    },
    {
      "id": "eg-005-versace-crystal-noir-edp",
      "name": "Versace Crystal Noir EDP",
      "brand": "Versace",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "90 ml",
      "year": 2004,
      "priceSar": 252,
      "rating": 5.0,
      "ratingCount": 5,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/v/e/versace_crystal_noir_eau_de_toilette_1.jpg",
      "description": "An oriental floral fragrance for women, giving you the perfect sensuality and charm, with a wonderful mixture of cardamom, peony, musk, and amber.",
      "notes": [
        "amber",
        "cardamom",
        "coconut",
        "gardenia",
        "ginger",
        "musk",
        "orange buds",
        "peony",
        "pepper",
        "sandalwood"
      ],
      "ingredients": "ginger, cardamom, pepper, orange buds, peony, gardenia, coconut, sandalwood, musk, amber."
    },
    {
      "id": "eg-006-boucheron-quatre-pour-femme",
      "name": "Boucheron Quatre Pour Femme",
      "brand": "Boucheron",
      "gender": "Women",
      "family": "Fruity",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2015,
      "priceSar": 240,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_boucheron_perfumes_quatre_pour_femme_for_women_eau_de_perfum.jpg",
      "description": "A fresh fragrance with delicious fruits of peach, strawberry, mandarin, orange, and apple that mixes with a soft and delicate scent of jasmine. This fragrance will touch your soul and adds...",
      "notes": [
        "apple",
        "caramel",
        "cashmere",
        "cedarwood",
        "grapefruit",
        "jasmine",
        "lemon",
        "mandarin",
        "orange",
        "peach",
        "rose",
        "strawberry",
        "vanilla"
      ],
      "ingredients": "mandarin, orange, lemon, grapefruit, strawberry, rose, peach, jasmine, apple, cedar, vanilla, cashmere, caramel"
    },
    {
      "id": "eg-007-versace-dylan-blue-pour-homme",
      "name": "Versace Dylan Blue Pour Homme",
      "brand": "Versace",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "50 ml",
      "year": 2016,
      "priceSar": 245,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_versace_perfumes_dylan_blue_pour_homme_for_men_eau_de_toilette.jpg",
      "description": "Aromatic fragrance for men reflects the colors of the Mediterranean Sea and its civilizations and contains distinctive fresh scents that have a sensual nature that combines desire, passion...",
      "notes": [
        "ambrox",
        "black pepper",
        "calabrian bergamot",
        "fig leaves",
        "grapefruit",
        "incense",
        "mineral musks",
        "organic patchouli",
        "papyrus wood",
        "saffron",
        "tonka bean",
        "violet leaf"
      ],
      "ingredients": "water notes, calabrian bergamot, grapefruit, fig leaf, violet leaf, papyrus, patchouli, black pepper, ambroxan, musk, incense, tonka bean, saffron"
    },
    {
      "id": "eg-008-gucci-flora-by-gucci-edp",
      "name": "Gucci Flora By Gucci EDP",
      "brand": "Gucci",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2008,
      "priceSar": 302,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/u/gucci_flora_update-1.jpg",
      "description": "This sensual fragrance is dedicated for the woman who has a youthful, feminine spirit. It's inspired by the iconic Flora print of Gucci. It opens with mandarin and peony, then comes rose...",
      "notes": [
        "mandarin",
        "osmanthus flower",
        "patchouli",
        "peony",
        "pink pepper",
        "rose",
        "sandalwood",
        "vanilla"
      ],
      "ingredients": "mandarin, peony, rose, pink pepper, osmanthus flower, patchouli, sandalwood, vanilla"
    },
    {
      "id": "eg-009-elie-saab-le-parfum",
      "name": "Elie Saab Le Parfum",
      "brand": "Elie Saab",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2011,
      "priceSar": 222,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/e/l/elie_saab_le_parfum_eau_de_parfum_1.jpg",
      "description": "A strong long-lasting fragrance to express glowing femininty. It opens with radiant orange blossom, moving to jasmine in the heart, o end with the cedar, patchouli, and rose honey in the...",
      "notes": [
        "cedar",
        "grandiflorum",
        "jasmine",
        "orange blossom",
        "patchouli",
        "rose honey",
        "sambac"
      ],
      "ingredients": "orange blossom, jsmine, grandiflorum, sambac, cedar, patchouli, rose honey"
    },
    {
      "id": "eg-010-lancome-idole",
      "name": "Lancome Idole",
      "brand": "Lancome",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2019,
      "priceSar": 412,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3614272629387-lancome-idole-edp.jpg",
      "description": "This modern chypre-floral perfume marks a new generation of fragrances, delivering a message of strong and powerful feminity for those who dream big. The luminous aroma results in a scent...",
      "notes": [
        "bergamot (citrus)",
        "cedarwood",
        "jasmine",
        "juicy pear",
        "patchouli",
        "pink peppercorn",
        "rose",
        "vanilla",
        "white musk"
      ],
      "ingredients": "bergamot (citrus),juicy pear, pink peppercorn, rose, jasmine, white musk, vanilla, patchouli, cedarwood"
    },
    {
      "id": "eg-011-coach-for-men",
      "name": "Coach For Men",
      "brand": "Coach",
      "gender": "Men",
      "family": "Floral",
      "character": "Masculine",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 226,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/o/coach_coach_for_men_edt_100_ml.jpg",
      "description": "Launched in 2017 and featuring actor James Franco as the face of the fragrance, Coach for men, by Coach, is meant for the modern and sophisticated man. This elegant cologne starts with...",
      "notes": [
        "ambergris",
        "bergamot",
        "cardamom",
        "coriander (cilantro)",
        "geranium",
        "haitian vetiver",
        "kumquat",
        "pear",
        "suede"
      ],
      "ingredients": "pear, bergamot, kumquat, grapefruit, lavender, cardamom, coriander, geranium, haitian vetiver, suede, ambergris, amberwood."
    },
    {
      "id": "eg-012-dior-sauvage-edp",
      "name": "Dior Sauvage EDP",
      "brand": "Dior",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2015,
      "priceSar": 430,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/s/gs-award-020-perfumes-products-sauvage.jpg",
      "description": "The powerful freshness of Sauvage EDP by Dior exudes new sensual and mysterious facets, sufficiently renewing itself with the signature of an ingenious composition. Calabrian bergamot, as...",
      "notes": [
        "ambroxan",
        "bergamot",
        "lavender",
        "nutmeg",
        "sichuan pepper",
        "star anise",
        "vanilla"
      ],
      "ingredients": "bergamot,lavender, nutmeg, sichuan pepper, star anise,vanilla, ambroxan"
    },
    {
      "id": "eg-013-cartier-la-panthere",
      "name": "Cartier La Panthere",
      "brand": "Cartier",
      "gender": "Women",
      "family": "Floral",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "75 ml",
      "year": 2014,
      "priceSar": 483,
      "rating": 5.0,
      "ratingCount": 4,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/cartier_la_panthere_eau_de_parfum_1.jpg",
      "description": "Cartier La Panthere was launched by the established Cartier brand in 2014. A feline floral fragrance born out of radiant, delicate gardenia coming together with velvety notes of musk...",
      "notes": [
        "apple",
        "apricot",
        "dry fruits",
        "gardenia",
        "musk ketone",
        "oakmoss",
        "rhubarb",
        "strawberry"
      ],
      "ingredients": "apple, apricot, strawberry, rhubarb, dry fruits,gardenia,oakmoss, musk ketone"
    },
    {
      "id": "eg-014-yves-saint-laurent-libre",
      "name": "Yves Saint Laurent Libre",
      "brand": "Yves Saint Laurent",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "90 ml",
      "year": 2019,
      "priceSar": 389,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3614272648418c-yves-saint-laurent-libre---90-ml_1_.jpg",
      "description": "This perfume is a reflection of Freedom, specially designed for bold women, for those who live by their own rules, to enjoy the unique fusion of French lavender & orange blossoms from...",
      "notes": [
        "ambergris",
        "black currant",
        "cedar",
        "jasmine",
        "lavendar",
        "mandarin orange",
        "musk",
        "orange blossom",
        "petitgrain",
        "vanilla"
      ],
      "ingredients": "mandarin orange, lavendar, black currant, petitgrain, jasmine, orange blossom, vanilla, cedar, musk, ambergris"
    },
    {
      "id": "eg-015-giorgio-armani-emporio-armani-stronger-with-you-intensely",
      "name": "Giorgio Armani Emporio Armani Stronger With You Intensely",
      "brand": "Giorgio Armani",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 399,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3614272225718-giorgio-armani-emporio-armani-stronger-with-you-intensely.jpg",
      "description": "for every romantic gentle man, This strong fascinating fragrance is for you. It was released to capture all people hearts from the first smell to tell a story of an outstanding emotional...",
      "notes": [
        "amber",
        "cinnamon",
        "juniper",
        "lavender",
        "pink pepper",
        "sage",
        "suede",
        "toffee",
        "tonka bean",
        "vanilla",
        "violet leaf"
      ],
      "ingredients": "spices, violet, lavender, sweet toffee, caramel, cinnamon, suede, vanilla, amber"
    },
    {
      "id": "eg-016-roberto-cavalli-paradiso-azzurro",
      "name": "Roberto Cavalli Paradiso Azzurro",
      "brand": "Roberto Cavalli",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2015,
      "priceSar": 174,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_roberto_cavalli_perfumes_paradiso_azzurro_for_women_eau_de_parfum.jpg",
      "description": "A floral fragrance for women inspired by the pictures of the golden light of the sunrise over the blue Mediterranean waters, with its enchanting blend of bergamot, peach, Kashmiri wood and...",
      "notes": [
        "bergamot",
        "cashmere woods",
        "citrus",
        "cypress",
        "lavender",
        "petals",
        "wild jasmine"
      ],
      "ingredients": "citrus freshness, bergamot, lavender, wild jasmine, petals, cypress, cashmere."
    },
    {
      "id": "eg-017-gucci-guilty-intense",
      "name": "Gucci Guilty Intense",
      "brand": "Gucci",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2011,
      "priceSar": 323,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_gucci_perfumes_gucci_guilty_intense_eau_de_parfum.jpg",
      "description": "This floral oriental scent is made up of intense and powerful dose of pink pepper and lilac, which comes in a bottle that replicates the fusion of metal and smoky grey glass. It opens with...",
      "notes": [
        "ambery notes",
        "geranium",
        "lilac",
        "mandarin",
        "patchouli",
        "peach",
        "pink pepper"
      ],
      "ingredients": "mandarin, pink pepper, peach, lilac, geranium, ambery notes, patchouli"
    },
    {
      "id": "eg-018-mont-blanc-legend-night",
      "name": "Mont Blanc Legend Night",
      "brand": "Mont Blanc",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Extravagant",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 401,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_mont_blanc_perfumes_legend_night_for_men_eau_de_perfum_3386460087940.jpg",
      "description": "This perfume is a classic fragrance for men. The blend of natural elements including peppermint, cardamom, and bergamot giving natural radiant aroma. High notes consist of clary sage...",
      "notes": [
        "akigalawood",
        "apple",
        "bergamot",
        "black vanilla",
        "cardamom",
        "cedar",
        "clary sage",
        "fir",
        "lavender",
        "musk",
        "patchouli",
        "peppermint",
        "vetiver",
        "violet"
      ],
      "ingredients": "bergamot, sage,cardamom,cedar,lavender,violet,apple,fir resin,vetiver,black vanilla,husk,patchoulli,musk."
    },
    {
      "id": "eg-019-calvin-klein-eternity-men",
      "name": "Calvin Klein Eternity Men",
      "brand": "Calvin Klein",
      "gender": "Women",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 1990,
      "priceSar": 152,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/calvin_klein_eternity_for_men_eau_de_toilette.jpg",
      "description": "A fragrance that embodies the spirit and life of the modern man, as it is a fragrance full of masculinity and vitality, and enhances the sense of confidence, as it carries a classic and...",
      "notes": [
        "amber",
        "basil",
        "geranium",
        "green botanics",
        "jasmine",
        "lavender",
        "mandarin",
        "rosewood",
        "sage",
        "sandalwood",
        "vetiver"
      ],
      "ingredients": "mandarin, lavender, green botanics, jasmine, basil, geranium, sage, sandalwood, vetiver, rosewood, amber"
    },
    {
      "id": "eg-020-hermes-terre-d-hermes",
      "name": "Hermes Terre D'Hermes",
      "brand": "Hermes",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "50 ml",
      "year": 2006,
      "priceSar": 375,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/a/a/aaaaa.jpg",
      "description": "Hermes Terre D'Hermes has a scent with a combination of wood and softness of benzoin and the sparkle of shiso. It gives warmth and delightful feeling with its scent.",
      "notes": [
        "atlas cedarwood",
        "baies rose",
        "flint",
        "geranium leaves",
        "grapefruit",
        "gum benzoin",
        "gunflint",
        "orange",
        "patchouli",
        "peppers",
        "pink peppercorn",
        "vetiver"
      ],
      "ingredients": "grapefruit, orange, gunflint, flint, peppers, pink peppercorn, geranium leaves, patchouli, baies rose, atlas cedarwood, vetiver, gum benzoin"
    },
    {
      "id": "eg-021-giorgio-armani-acqua-di-gio-profumo",
      "name": "Giorgio Armani Acqua Di Gio Profumo",
      "brand": "Giorgio Armani",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "125 ml",
      "year": 2015,
      "priceSar": 524,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/i/giorgio_armani_acqua_di_gio_homme__profumo.jpg",
      "description": "Acqua di Gio Profumo is an aquatic, aromatic, woody and spicy composition which is, like the original, signed by Alberto Morillas. It opens with fresh aquatic accord and bergamot. Its heart...",
      "notes": [
        "aquatic notes",
        "bergamot",
        "geranium",
        "incense",
        "patchouli",
        "rosemary",
        "sage"
      ],
      "ingredients": "bergamot , sea notes, geranium,rosemary,sage, patchouli,incense,"
    },
    {
      "id": "eg-022-valentino-uomo",
      "name": "Valentino Uomo",
      "brand": "Valentino",
      "gender": "Men",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "50 ml",
      "year": 2011,
      "priceSar": 342,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/v/a/valentino_uomo_eau_de_toilette_1.jpg",
      "description": "Valentino Uomo Eau de Toilette is a fresh fragrance for men, presented in a magnificent bottle. This modern scent is developed for a cosmopolitan man celebrating his youthful vigor and...",
      "notes": [
        "bergamot",
        "cedar",
        "chocolate",
        "hazelnut",
        "leather",
        "myrtle",
        "roasted coffee beans"
      ],
      "ingredients": "bergamot, myrtle ,roasted coffee beans, chocolate, hazelnut ,leather, cedar"
    },
    {
      "id": "eg-023-jaguar-classic-red",
      "name": "Jaguar Classic Red",
      "brand": "Jaguar",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2016,
      "priceSar": 89,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_jaguar_perfumes_classic_red_for_women_eau_de_toilette.jpg",
      "description": "Jaguar Classic Red is a floral-fruity and woody fragrance for men. The scent is warm, sweet, fruity, deep, long-lasting, characterful, and unique. Classic Red is created for a man living...",
      "notes": [
        "bay and hot pepper oil",
        "bergamot",
        "blackcurrant",
        "cedarwood",
        "jasmine leaves",
        "ozonic accord",
        "patchouli",
        "raspberry",
        "white amber"
      ],
      "ingredients": "raspberry, blueberry, bergamot, jasmine, black pepper, patchouli, cedar, amber, tonka bean, vanilla"
    },
    {
      "id": "eg-024-gucci-guilty-absolute-pour-homme",
      "name": "Gucci Guilty Absolute Pour Homme",
      "brand": "Gucci",
      "gender": "Men",
      "family": "Woody",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2017,
      "priceSar": 418,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/u/gucci_guilty_absolute_eau_de_parfum.png",
      "description": "This fragrance embodies the modern declaration of self-expression. It's made for the liberated man who who defines his own masculinity. It features leather notes in the opening, leading to...",
      "notes": [
        "goldenwood",
        "leather",
        "patchouli cypress",
        "vetiver"
      ],
      "ingredients": "leather, patchouli, cypress, vetiver, golden wood"
    },
    {
      "id": "eg-025-lalique-encre-noir",
      "name": "Lalique Encre Noir",
      "brand": "Lalique",
      "gender": "Men",
      "family": "Oriental",
      "character": "Masculine",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2005,
      "priceSar": 165,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_lalique_perfumes_encre_noir_for_men_eau_de_toilette.jpg",
      "description": "Lalique Encre Noir is a breathtaking woody, aromatic scent for men. The opening notes are fresh and woody thanks to Cypress and Vetiveryl Acetate. At the heart, Haiti Vetyver and Bourbon...",
      "notes": [
        "bourbon vetyver",
        "cashmere wood",
        "cypress",
        "haiti vetyver",
        "musks",
        "vetiveryl acetate"
      ],
      "ingredients": "vetiver, cypress, cashmere wood, musk"
    },
    {
      "id": "eg-026-ad-astra-by-minis",
      "name": "Ad Astra By Minis",
      "brand": "Minis",
      "gender": "Men",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 80,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/small_image/750x750/9df78eab33525d08d6e5fb8d27136e95/a/d/ad-astra1.png",
      "description": "Stars were always the fascination of the wanderers. Ever since mythical stories were wrapped around the stars, \"Ad Astra\u00c3\u00a2\u00e2\u201a\u00ac\u00c2\u009d is your journey towards the stars. This set was created for...",
      "notes": [
        "unknown"
      ],
      "ingredients": "unknown"
    },
    {
      "id": "eg-027-perfume-co-honey-tobacco-edp",
      "name": "Perfume Co. Honey Tobacco EDP",
      "brand": "Perfume Co.",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Sophisticated",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 149,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/p/e/perfume-co-honey-tobacco.png",
      "description": "Designed for a modern persona, imaginary yet luxurious. The opening note of ylang-ylang richness & the sweet decay of gardenia blends effortlessly with the sophisticated scent of incense.",
      "notes": [
        "gardenia",
        "tuberose incense",
        "ylang-ylang"
      ],
      "ingredients": "ylang-ylang, gardenia, tuberose incense"
    },
    {
      "id": "eg-028-who-am-i-just-right-edp",
      "name": "Who Am I Just Right EDP",
      "brand": "The Different Company",
      "gender": "Men",
      "family": "Citrus",
      "character": "Dynamic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 149,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/w/h/who_am_i_just_right_1.jpg",
      "description": "Descritpion: Who Am I? In this modern world, who do I choose to be in this chaos! I am the line between aquatic freshness & forest depths. I draw Just the Right balance blending bergamot...",
      "notes": [
        "bergamot",
        "marine acqua",
        "oakmoss"
      ],
      "ingredients": "bergamot, marine acqua, oakmoss"
    },
    {
      "id": "eg-029-bvlgari-man-in-black",
      "name": "Bvlgari Man In Black",
      "brand": "Bvlgari",
      "gender": "Men",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "60 ml",
      "year": 2017,
      "priceSar": 270,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/v/bvlgari_man_in_black.jpg",
      "description": "A floral oriental fragrance with sweet rum and warm spices that give an irresistible masculine appearance. This fragrance combines tuberose and iris that adds romantic and charismatic for...",
      "notes": [
        "benzene",
        "diabetic rum",
        "guaiac wood",
        "iris",
        "leather",
        "spices",
        "tobacco",
        "tonka beans",
        "tuberose"
      ],
      "ingredients": "diabetic rum, spices, tobacco, iris, tuberose, leather, tonka beans, benzene, guaiac wood"
    },
    {
      "id": "eg-030-s-t-dupont-essence-pure-pour-femme",
      "name": "S.T. Dupont Essence Pure Pour Femme",
      "brand": "S.T. Dupont",
      "gender": "Women",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2008,
      "priceSar": 311,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/t/st_dupont_essence_pure.jpg",
      "description": "Essence Pure Pour Femme by S.T. Dupont is an Oriental Floral fragrance for women. This heavenly scent was developed just for you. The opening of the fragrance is sparkling and citrusy with...",
      "notes": [
        "amber",
        "bergamot",
        "cedar",
        "freesia",
        "jasmine",
        "mandarin orange",
        "patchouli",
        "rose",
        "vanilla"
      ],
      "ingredients": "mandarin orange, freesia, bergamot ,jasmine, rose, amber, patchouli, vanilla, cedar"
    },
    {
      "id": "eg-031-very-important-notes-no-4-edp",
      "name": "Very Important Notes No 4 EDP",
      "brand": "Very Important Notes",
      "gender": "Unisex",
      "family": "Oriental",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2020,
      "priceSar": 295,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/v/i/vin_4-ver2-3.jpg",
      "description": "For the rebel soul in you. This fragrance is the most evoking scent from this collection. It started with a quest to find a true adventurous fragrance. This scent emerged to fulfill this...",
      "notes": [
        "amber",
        "cedarwood",
        "green coffee accord",
        "oud accord",
        "smokey note",
        "tobbaco",
        "vetiver"
      ],
      "ingredients": "green coffee accord ,cedarwood, tobbaco, vetiver ,amber, oud accord, smokey note"
    },
    {
      "id": "eg-032-ajmal-raindrops",
      "name": "Ajmal Raindrops",
      "brand": "Ajmal",
      "gender": "Women",
      "family": "Floral",
      "character": "Glamorous",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2006,
      "priceSar": 46,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_ajmal_perfumes_raindrops_spray_for_women_6293708001712.jpg",
      "description": "Ajmal Raindrops An awesome perfume with unique floral, fruity and sensual notes for the ultra-modern woman of today. A modern scent, which exudes a sleek and simplistic elegance enveloping...",
      "notes": [
        "ambergris",
        "floral notes",
        "fruity notes",
        "woodsy notes"
      ],
      "ingredients": "floral notes , woodsy notes, fruity notes, ambergris"
    },
    {
      "id": "eg-033-bvlgari-man-in-black-limited-edition-essence",
      "name": "Bvlgari Man In Black Limited Edition Essence",
      "brand": "Bvlgari",
      "gender": "Men",
      "family": "Woody Oriental",
      "character": "Sophisticated",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 398,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/v/bvlgari_man_in_black_limited_edition_essence_edp_100_ml.jpg",
      "description": "Ana Oriental Spicy fragrance that combines with spices and sweet rum. This fragrance mixes with resin and guaiac wood that gives warm and fresh scent with a delicate touch of flowers and...",
      "notes": [
        "diabetic rum",
        "guaiac wood",
        "gum",
        "musk",
        "oriental scents",
        "roses",
        "spices"
      ],
      "ingredients": "spices, flowers, musk, oriental notes, resin, guaiac wood."
    },
    {
      "id": "eg-034-burberry-her",
      "name": "Burberry Her",
      "brand": "Burberry",
      "gender": "Women",
      "family": "Fruity",
      "character": "Glamorous",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2018,
      "priceSar": 516,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3614227693876_burberry_burberry_her_edp_100_ml.jpg",
      "description": "for you, this feminine fragrance full of life and elegance, let your spirit unleash this delightful blend of fruit and woody notes, a wonderful and indispensable fragrance in the spring and...",
      "notes": [
        "amber",
        "blackberry",
        "blueberry",
        "cherry",
        "jasmine",
        "musk",
        "raspberry",
        "strawberry",
        "violet",
        "woods"
      ],
      "ingredients": "raspberry, strawberry, sour cherry, blackberry, black currant, lemon, mandarin, orange, jasmine, violet, amber, musk, patchouli, vanilla"
    },
    {
      "id": "eg-035-calvin-klein-ck-be",
      "name": "Calvin Klein Ck Be",
      "brand": "Calvin Klein",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "200 ml",
      "year": 1996,
      "priceSar": 103,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/calvin_klein_be.jpg",
      "description": "A limited edition in a distinctive and interesting collection entitled \"We are one\" as a sign of liberation and equality and engraving the title on the packages in several international...",
      "notes": [
        "bergamot",
        "juniper berry",
        "lavender",
        "light spices",
        "magnolia",
        "mandarin",
        "mint",
        "opoponax",
        "peach",
        "sandalwood",
        "tonka bean",
        "white musk"
      ],
      "ingredients": "lavender, musk, sandalwood, green notes, bergamot, mint"
    },
    {
      "id": "eg-036-lanc-me-la-nuit-tresor",
      "name": "Lanc\u00c3\u0192\u00c2\u00b4me La Nuit Tresor",
      "brand": "Lancome",
      "gender": "Women",
      "family": "Oriental",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "75 ml",
      "year": 2015,
      "priceSar": 445,
      "rating": 5.0,
      "ratingCount": 3,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/a/lanc_me_la_nuit_tr_sor.jpg",
      "description": "Lancome launches La Nuit Tresor fragrance in February 2015. The scent is a flanker of the original Tresor from 1990. The composition is announced as a gourmand aphrodisiac and a love potion...",
      "notes": [
        "absolute vanilla orchid tahitensis",
        "incense",
        "lychee",
        "papyrus",
        "patchouli",
        "praline",
        "raspberry",
        "rose damascena essence"
      ],
      "ingredients": "lychee, raspberry, rose damascena essence, incense, absolute vanilla orchid tahitensis, praline, patchouli, papyrus"
    },
    {
      "id": "eg-037-the-finest-rose-edp",
      "name": "The Finest Rose EDP",
      "brand": "The Finest",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 249,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/t/h/the-finest-rose.jpg",
      "description": "\"Luxurious, Floral and soft\" A fragrant blend with endless creativity! Luxurious with its saffron component, Floral thanks to its Bulgarian rose notes and lilies, and soft from its...",
      "notes": [
        "bulgarian rose",
        "musk",
        "saffron"
      ],
      "ingredients": "saffron, bulgarian rose, musk"
    },
    {
      "id": "eg-038-maqam-base-of-poetry-edp",
      "name": "Maqam Base of Poetry EDP",
      "brand": "Maqam",
      "gender": "Men",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "120 ml",
      "year": 2020,
      "priceSar": 319,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/maqam_base_of_poetry-2.png",
      "description": "A romantic fragrance that conveys a beautiful mystical blend. A harmonious balance filled with appealing Arabian notes, easily distinguished from other oriental scents. In the beginning, it...",
      "notes": [
        "cinammon",
        "clove",
        "musk",
        "orange",
        "rose",
        "vanilla"
      ],
      "ingredients": "orange, cinammon, rose, clove, musk, vanilla"
    },
    {
      "id": "eg-039-remal-oud-wood-bakhoor",
      "name": "Remal Oud Wood Bakhoor",
      "brand": "Remal",
      "gender": "Unisex",
      "family": "Oriental",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2020,
      "priceSar": 125,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/small_image/750x750/9df78eab33525d08d6e5fb8d27136e95/r/e/remal_oud_wood_2.jpg",
      "description": "Created from the finest oud wood, this classical incense is refined and long-lasting. It is distinguished by its woody aromatic fragrance, blended harmoniously with musk and amber, for a...",
      "notes": [
        "agarwood",
        "amber",
        "musk"
      ],
      "ingredients": "agarwood, musk, amber"
    },
    {
      "id": "eg-040-givenchy-hot-couture",
      "name": "Givenchy Hot Couture",
      "brand": "Givenchy",
      "gender": "Women",
      "family": "Fruity",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2000,
      "priceSar": 274,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/i/givenchy_hot_couture_edp.jpg",
      "description": "Hot Couture was introduced in 2000. This women\u00c3\u00a2\u00e2\u201a\u00ac\u00e2\u201e\u00a2s fragrance is chic, sexy and oh, so French. Top notes are bright, succulent and fruity. Raspberry and mandarin are the ideal...",
      "notes": [
        "amber",
        "bergamot",
        "black pepper",
        "magnolia",
        "musk",
        "orange",
        "raspberry",
        "sandalwood",
        "vetiver"
      ],
      "ingredients": "bergamot, raspberry, orange, magnolia, black pepper, vetiver,amber, musk, sandalwood"
    },
    {
      "id": "eg-041-calvin-klein-ck-beauty",
      "name": "Calvin Klein Ck Beauty",
      "brand": "Calvin Klein",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 121,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_calvin_klein_perfumes_beauty_for_women_eua_de_parfum-1.jpg",
      "description": "A modern perfume full of confidence and luster, it is a mixture of femininity and sophistication because it reflects the inner and outer spirit and beauty of women with its amazing...",
      "notes": [
        "jasmine",
        "orange blossom",
        "sandalwood",
        "vetiver",
        "ylang-ylang"
      ],
      "ingredients": "ylang-ylang, orange blossom, jasmine, sandalwood, vetiver"
    },
    {
      "id": "eg-042-roberto-cavalli-paradiso-assoluto",
      "name": "Roberto Cavalli Paradiso Assoluto",
      "brand": "Roberto Cavalli",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "75 ml",
      "year": 2016,
      "priceSar": 137,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_roberto_cavalli_perfumes_paradiso_assoluto_for_women_eau_de_perfum.jpg",
      "description": "A chypre floral fragrance that represents the scents of a heavenly garden by its generous nature and dense flowers, and gives you an amazing refreshment, with a mixture of pink pepper, wild...",
      "notes": [
        "bergamot",
        "cashmere wood",
        "grapefruit",
        "istria",
        "lemon",
        "love fruit",
        "patchouli",
        "pink pepper",
        "red lily",
        "sandalwood",
        "vanilla",
        "wild jasmine"
      ],
      "ingredients": "pink pepper, istria, bergamot, grapefruit, lemon, wild jasmine, red lily, love fruit, patchouli, sandalwood, vanilla, cashmere wood."
    },
    {
      "id": "eg-043-burberry-london",
      "name": "Burberry London",
      "brand": "Burberry",
      "gender": "Women",
      "family": "Floral",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2006,
      "priceSar": 170,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/u/burberry-burberry_london_for_woman_edp.jpg",
      "description": "A magical fragrance that reflects an elegant and exciting nature, thanks to the fresh notes of fresh Clementine oil mixed with rose extract enriched with the sweetness of honey blossom, to...",
      "notes": [
        "clementine",
        "english garden rose",
        "honeysuckle",
        "indian sandalwood",
        "jasmine",
        "musks",
        "patchouli",
        "peony",
        "tiare flower"
      ],
      "ingredients": "rose, honeysuckle, tangerine, jasmine, clementine, musk, patchouli, sandalwood"
    },
    {
      "id": "eg-044-candy-addict-v-vanille-edp",
      "name": "Candy Addict V Vanille EDP",
      "brand": "Candy Addict",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2021,
      "priceSar": 139,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/ca-v-vanille-edp-1.jpg",
      "description": "An intoxicating blend of vanilla and floral notes with a touch of Oriental! Take your perfume game to a whole new level with this one of a kind fragrance sensation.",
      "notes": [
        "pink pepper",
        "sage",
        "vanilla"
      ],
      "ingredients": "pink pepper, sage, vanilla"
    },
    {
      "id": "eg-045-narciso-rodriguez-pure-musc-for-her",
      "name": "Narciso Rodriguez Pure Musc For Her",
      "brand": "Narciso Rodriguez",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2019,
      "priceSar": 385,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_narciso_rodriguez_perfumes_pure_musc_for_her_for_women_3423478504158.jpg",
      "description": "Pure Musc for Her is a Floral Woody Musk fragrance for women. This is a new fragrance with top notes of musk and middle notes of flowers and a base of cashmeran.",
      "notes": [
        "amber",
        "cashmeran",
        "jasmine",
        "musk",
        "orange blossom",
        "patchouli"
      ],
      "ingredients": "jasmine, orange blossom, musk, cashmeran, amber, patchouli"
    },
    {
      "id": "eg-046-burberry-body-tender",
      "name": "Burberry Body Tender",
      "brand": "Burberry",
      "gender": "Women",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "85 ml",
      "year": 2013,
      "priceSar": 175,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/u/burberry_body_tender.jpg",
      "description": "A youthful feminine fragrance that gives you a feeling of vitality and elegance thanks to its harmonious blend of flowers and fruits, such as fresh English roses, with white jasmine and...",
      "notes": [
        "amber and musk",
        "english roses",
        "fresh apples",
        "green aventine",
        "lemon",
        "sandalwood",
        "white jasmine"
      ],
      "ingredients": "english roses, white jasmine, sandalwood, lemon, fresh apples, green aventine, amber and musk"
    },
    {
      "id": "eg-047-marly-delina",
      "name": "Marly Delina",
      "brand": "Parfums de Marly",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "75 ml",
      "year": 2017,
      "priceSar": 1265,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/marly_marly_delina_edp_75_ml.jpg",
      "description": "This feminine floral fragrance adds tender and romance touches that enchants who you love, making you feel attractive and desirable.",
      "notes": [
        "bergamot",
        "cashmere",
        "cedarwood",
        "haitian vetiver",
        "incense",
        "litchi",
        "musk",
        "nutmeg",
        "peony",
        "petalia",
        "rhubarb",
        "turkish rose",
        "vanilla"
      ],
      "ingredients": "bergamot, rhubarb, litchi, nutmeg, turkish rose, peony, petalia, vanilla, musk, cashmere, haitian vetiver, cedar wood, incense."
    },
    {
      "id": "eg-048-guerlain-oud-essentiel",
      "name": "Guerlain Oud Essentiel",
      "brand": "Guerlain",
      "gender": "Unisex",
      "family": "Woody",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "125 ml",
      "year": 2000,
      "priceSar": 862,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_guerlain_perfumes_oud_essentiel_for_women_eau_de_perfum-3346470132245.jpg",
      "description": "Guerlain Oud Essentiel is a unisex oriental, woody fragrance. It brings the East and West together in a beautiful paradox. Oud is a mysterious and exotic element that is always a winning...",
      "notes": [
        "atlas cedar",
        "bulgarian rose",
        "frankincense",
        "gaiac wood",
        "geranium",
        "leather",
        "oud",
        "saffron"
      ],
      "ingredients": "saffron, geranium,oud, bulgarian rose, atlas cedar,leather, frankincense, gaiac wood"
    },
    {
      "id": "eg-049-marly-delina-exclusif-royal",
      "name": "Marly Delina Exclusif Royal",
      "brand": "Parfums de Marly",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "75 ml",
      "year": 2018,
      "priceSar": 1438,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_marly_perfumes_delina_exclusif_royal_essence_for_women_perfum_3700578522009_1.jpg",
      "description": "This dreamy floral fragrance gives you a strong sensual and irresistible seduction with its oriental beauty scent that adds excitement and passion in your romantic evening.",
      "notes": [
        "amber",
        "bergamot",
        "incense",
        "litchi",
        "oud",
        "pear",
        "turkish rose",
        "vanilla",
        "woods"
      ],
      "ingredients": "bergamot, pear, litchi, turkish rose, incense, oud, woods, amber, vanilla."
    },
    {
      "id": "eg-050-tom-ford-oud-wood",
      "name": "Tom Ford Oud Wood",
      "brand": "Tom Ford",
      "gender": "Unisex",
      "family": "Woody",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2007,
      "priceSar": 1104,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_tom_ford_perfumes_oud_wood_for_unisex_eau_de_perfum.jpg",
      "description": "Tom Ford Oud Wood parfume is a unisex fragrance that contains ingredients such as Oud wood which is considered one of the most rare, precious and costly ingredient in the parfume industry...",
      "notes": [
        "brazilian rosewood",
        "cardamom",
        "oud",
        "sandalwood",
        "sichuan pepper",
        "tonka",
        "vanilla and amber",
        "vetiver"
      ],
      "ingredients": "oud, brazilian rosewood, cardamom, sichuan pepper, sandalwood, vetiver, tonka, vanilla and amber."
    },
    {
      "id": "eg-051-viktor-rolf-flower-bomb",
      "name": "Viktor & Rolf Flower Bomb",
      "brand": "Viktor & Rolf",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2005,
      "priceSar": 492,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/v/i/viktor_rolf_flowerbomb_eau_de_parfum_2.jpg",
      "description": "An oriental floral fragrance made from high quality essential oils, it is considered one of the best selling parfumes in the world. FlowerBomb is a perfect fit for anything you wear...",
      "notes": [
        "african orange flower",
        "bergamot",
        "freesia",
        "jasmine",
        "musk and patchouli",
        "rose and orchid",
        "tea and ottamentos"
      ],
      "ingredients": "bergamot, tea, ottamentos, jasmine, african orange flower, freesia, rose, orchid, musk and patchouli"
    },
    {
      "id": "eg-052-guerlain-mon-guerlain",
      "name": "Guerlain Mon Guerlain",
      "brand": "Guerlain",
      "gender": "Women",
      "family": "Woody Oriental",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2016,
      "priceSar": 483,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_guerlain_perfumes_mon_guerlain_for_woman_eau_de_parfum.jpg",
      "description": "Guerlain Mon Guerlain is an ideal perfume for an inspirational woman. This fragrance was inspired by women\u00c3\u00a2\u00e2\u201a\u00ac\u00e2\u201e\u00a2s dreams, ambitions and choices. It delivers an elixir for elegance and...",
      "notes": [
        "australian sandalwood",
        "bergamot",
        "indian jasmine sambac",
        "iris",
        "tahitian vanilla",
        "true lavender"
      ],
      "ingredients": "vanilla, lavender, coumarin, iris, australian sandalwood, jasmine sambac, bergamot"
    },
    {
      "id": "eg-053-elizabeth-arden-5th-avenue",
      "name": "Elizabeth Arden 5Th Avenue",
      "brand": "Elizabeth Arden",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "125 ml",
      "year": 2017,
      "priceSar": 145,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_elizabeth_arden_perfumes_5th_avenue_for_women_eau_de_parfum_4.jpg",
      "description": "5th Avenue fragrance is the symbol of wealth. This floral perfume is for the intelligent, successful and elegant woman who has a unique sense of style. 5th Avenue celebrates a...",
      "notes": [
        "amber",
        "bergamot",
        "bulgarian rose",
        "clove",
        "indian tuberose",
        "iris",
        "jasmine",
        "lilac",
        "lily-of-the-valley",
        "linden blossom",
        "magnolia",
        "mandarin",
        "nutmeg",
        "peach"
      ],
      "ingredients": "amber, sandalwood, lily of the valley, ylang-ylang, bergamot"
    },
    {
      "id": "eg-054-kun-safi-tobacco-safi-perfume-oil",
      "name": "Kun Safi Tobacco Safi Perfume Oil",
      "brand": "Kun Safi",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Perfume Oil",
      "size": "1.7 Tola / 20g",
      "year": 2020,
      "priceSar": 80,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/k/u/kun-safi-tobacco.png",
      "description": "\u00c3\u00a2\u00e2\u201a\u00ac\u00c5\u201cDiscover Tobacco scent.. Discover Power\u00c3\u00a2\u00e2\u201a\u00ac\u00c2\u009d Pure Luxurious perfume oil extracted from tobacco leaves, granting you an authentic scent of power & strength. This oil was designed...",
      "notes": [
        "amber",
        "green apple",
        "sandalwood",
        "tobacco"
      ],
      "ingredients": "green apple, amber, tobacco, sandalwood"
    },
    {
      "id": "eg-055-gucci-bloom-ambrosia-di-fiori",
      "name": "Gucci Bloom Ambrosia di Fiori",
      "brand": "Gucci",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 428,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3614228958691_gucci_bloom_ambrosia_di_fiori_edp_100_ml_1.jpg",
      "description": "This floral fragrance is inspired by the freedom of being who you really are. It invites you to celebrate your true self and the emotions you feel. It features new ingredients like the rare...",
      "notes": [
        "damask rose",
        "indian tuberose",
        "jasmine bud",
        "rangoon creeper",
        "tuscan orris"
      ],
      "ingredients": "jasmine bud, rangoon creeper, indian tuberose, tuscan orris, damask rose"
    },
    {
      "id": "eg-056-one-word-moonglade-edp",
      "name": "One Word Moonglade EDP",
      "brand": "One Word",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 100,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/o/n/one_word_moonglade_1.jpg",
      "description": "From the dawn of time, Moonglade was always a scene to admire. This fragrance was inspired by this magical moment, sensual like this unusual composition of the delicious aroma freesia &...",
      "notes": [
        "freesia",
        "musks",
        "sandalwood"
      ],
      "ingredients": "freesia, musks, sandalwood"
    },
    {
      "id": "eg-057-uniqo-corallo-edp",
      "name": "Uniqo Corallo EDP",
      "brand": "Uniqo",
      "gender": "Women",
      "family": "Fruity",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 110,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/u/n/uniqo-corallo.png",
      "description": "A unique scent inspired by one of nature's iconic creatures Corallo (Corals in Italian). Extraordinary yet fragile, blending exquisite scents like bergamot, grasse rose & vetiver.",
      "notes": [
        "bergamot",
        "grasse rose",
        "vetiver"
      ],
      "ingredients": "bergamot, grasse rose, vetiver"
    },
    {
      "id": "eg-058-dunhill-desire",
      "name": "Dunhill Desire",
      "brand": "Dunhill",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2002,
      "priceSar": 189,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/d/u/dunhill_desire.jpg",
      "description": "Introduced in 2000, Desire for men, by Alfred Dunhill, is a confident, masculine scent for the new millennium. The top notes of heady bergamot, fresh lemon, orange blossoms, and crisp apple...",
      "notes": [
        "apple",
        "bergamot",
        "green lemon",
        "labdanum",
        "musk",
        "neroli",
        "patchouli",
        "rose",
        "teakwood",
        "vanilla"
      ],
      "ingredients": "apple, bergamot, green lemon, neroli,patchouli, rose, teakwood,labdanum, musk, vanilla"
    },
    {
      "id": "eg-059-coach-coach-women",
      "name": "Coach Coach Women",
      "brand": "Coach",
      "gender": "Women",
      "family": "Woody",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2017,
      "priceSar": 231,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_coach_perfumes_coach_women_edp_for_women_eau_de_perfum.jpg",
      "description": "Originally released in 2007, Coach perfume by Coach is a 2016 updated version that has a free-spirited and authentic attitude. Its fruity-floral scent is uplifting and refreshing with just...",
      "notes": [
        "musk",
        "pear",
        "pink pepper",
        "rasepberry leaf",
        "sandalwood",
        "turkish rose"
      ],
      "ingredients": "rasepberry leaf, pink pepper, pear,turkish rose,musk, sandalwood"
    },
    {
      "id": "eg-060-elie-saab-girl-of-now-shine",
      "name": "Elie Saab Girl Of Now Shine",
      "brand": "Elie Saab",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2018,
      "priceSar": 214,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_elie_saab_perfumes_girl_of_now_shine_for_women_eau_de_perfum_3423473095750.jpg",
      "description": "A luminous fragrance that chain all the eyes to you. It composes unique wonderful mix of scents in one beauty bottle that fit in any bag, so hat you can take wherever you go.",
      "notes": [
        "almond",
        "iris",
        "jasmine",
        "patchouli",
        "pear",
        "pineapple",
        "vanilla",
        "ylang- ylang"
      ],
      "ingredients": "pear, pineapple, almond, ylang- ylang, iris, jasmine, vanilla, patchouli"
    },
    {
      "id": "eg-061-dkhoun-thaty",
      "name": "Dkhoun Thaty",
      "brand": "Dkhoun",
      "gender": "Women",
      "family": "Woody",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 253,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/1/310029-dkhoun-_-_100ml-1.jpg",
      "description": "It's a special fragrance that is made from the base of luxurious natural musk and oriental oud. It will give you unlimited confidence and personalization.",
      "notes": [
        "blackberry trees",
        "cedar wood",
        "fine musk",
        "magnolia",
        "oud",
        "rose",
        "sandalwood",
        "whale amber"
      ],
      "ingredients": "blackberry trees, cedar wood, rose, magnolia, oud, fine musk, whale amber, sandalwood"
    },
    {
      "id": "eg-062-dkhoun-prime-max",
      "name": "Dkhoun Prime Max",
      "brand": "Dkhoun",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "85 ml",
      "year": 2017,
      "priceSar": 319,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/1/310064-dkhoun-_-_-85ml-1.jpg",
      "description": "This fragrance will provide a magnificent scent that you cannot resist. The amazing composition has notes of iris mixed with amber and musk, delivering an aromatic fragrance that captivates...",
      "notes": [
        "amber",
        "iris",
        "musk",
        "orchid",
        "pink pepper"
      ],
      "ingredients": "pink pepper, orchid, iris, musk, amber"
    },
    {
      "id": "eg-063-montale-vanilla-extasy",
      "name": "Montale Vanilla Extasy",
      "brand": "Montale",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2008,
      "priceSar": 478,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_montale_perfumes_vanilla_extasy_for_women_eau_de_perfum_m0060156b.jpg",
      "description": "Vanilla Extasy by Montale is a feminine oriental vanilla fragrance crafted by famous perfumer Pierre Montale. It was launched in the year 2008. The top notes of the perfume are apricot and...",
      "notes": [
        "apricot",
        "apricot blossom",
        "benzoin",
        "jasmine",
        "mahogany",
        "resins",
        "sandalwood",
        "vanilla",
        "ylang ylang"
      ],
      "ingredients": "apricot, apricot blossom, jasmine, ylang ylang, amber, benzoin, vanilla, mahogany, sandalwood"
    },
    {
      "id": "eg-064-kenzo-world-edt",
      "name": "Kenzo World EDT",
      "brand": "Kenzo",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "50 ml",
      "year": 2018,
      "priceSar": 356,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_kenzo_perfumes_kenzo_world_for_women_eau_de_toilette_3274872365049.jpg",
      "description": "This floral fragrance embodies excitment as it is designed for the woman who dares to be different, filling her with joy. Her need for enthusiasm attracts everyone through an amazing blend...",
      "notes": [
        "almond blossom",
        "bergamot",
        "orris root",
        "pear",
        "peony",
        "rose",
        "vanilla",
        "white musk"
      ],
      "ingredients": "red fruits, peony, floral notes, egyptian jasmine, ambroxan."
    },
    {
      "id": "eg-065-lolita-lempicka-lolita-lempicka",
      "name": "Lolita Lempicka Lolita Lempicka",
      "brand": "Lolita Lempicka",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 1997,
      "priceSar": 280,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/5/3595200113768_lolita_lempicka_lolita_lempicka_1.jpg",
      "description": "This soft floral scent will fill you with captivating smell full of happiness and joy. The wonderful combination of violet, amaryllis, along with cherry and praline will leave a charming...",
      "notes": [
        "amaryllis",
        "cherry",
        "iris",
        "ivy",
        "licorice",
        "orris root",
        "praline",
        "star anise",
        "tonka bean",
        "vanilla",
        "vetiver",
        "violet",
        "white musk"
      ],
      "ingredients": "violet, ivy, star anise, iris, amaryllis, licorice, orris root, cherry, vanilla, tonka bean, vetiver, white musk, praline"
    },
    {
      "id": "eg-066-mancera-pink-roses",
      "name": "Mancera Pink Roses",
      "brand": "Mancera",
      "gender": "Women",
      "family": "Floral",
      "character": "Feminine",
      "concentration": "Eau de Parfum",
      "size": "120 ml",
      "year": 2017,
      "priceSar": 437,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/mancera_pink_roses_120_ml.jpg",
      "description": "Mancera Pink Roses is a new floral fragrance, the Incredibly beautiful, heavy, warm perfume filled with very feminine notes. You will enjoy wearing it today and every day!:",
      "notes": [
        "amber",
        "bergamot",
        "bulgarian rose oil",
        "green notes",
        "mandarin",
        "moroccan rose absolute",
        "patchouli leaf",
        "pear",
        "violet",
        "white musk"
      ],
      "ingredients": "sparkling bergamot, mandarin, bulgarian rose oil, violet, pear, patchouli., white musk, amber."
    },
    {
      "id": "eg-067-creed-aventus",
      "name": "Creed Aventus",
      "brand": "Creed",
      "gender": "Men",
      "family": "Oud",
      "character": "Glamorous",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2011,
      "priceSar": 1938,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/5/3508441001114c-creed-aventus---100-ml.jpg",
      "description": "In honor of the brand's 250th anniversary, Creed came out with a stellar new cologne for elite gentlemen: Aventus. This cologne embodies the attitudes of success, vision, and strength. In...",
      "notes": [
        "ambergris",
        "apple",
        "bergamot",
        "birch",
        "blackcurrant leaves",
        "jasmine",
        "musk",
        "oakmoss",
        "patchouli",
        "pineapple",
        "pinkberries",
        "vanilla"
      ],
      "ingredients": "bergamot, blackcurrant leaves, apple, pineapple,pinkberries, birch, patchouli, jasmine,musk, oakmoss, ambergris, vanilla"
    },
    {
      "id": "eg-068-rasasi-al-wisam-day",
      "name": "Rasasi Al Wisam Day",
      "brand": "Rasasi",
      "gender": "Men",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 127,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/6/1/614514170021_rasasi_rasasi_al_wisam_day_white_men_100ml_1.jpg",
      "description": "To feel unique, confidence is your way. This fragrance enhances your confidence, leaving an unforgettable positive impression wherever you go. It offers you the spirit of the modern...",
      "notes": [
        "amber",
        "bergamot",
        "cedarwood",
        "clary sage",
        "geranium",
        "lavender",
        "musk",
        "oak moss",
        "oud",
        "rose",
        "sandalwood"
      ],
      "ingredients": "bergamot, lavender, geranium, rose, clary sage, sandalwood, cedarwood, amber, musk, oak moss, oud"
    },
    {
      "id": "eg-069-chopard-rose-malaki",
      "name": "Chopard Rose Malaki",
      "brand": "Chopard",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "80 ml",
      "year": 2014,
      "priceSar": 295,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/0/6/060314_1626_chopardrose2.jpg",
      "description": "This floral oriental fragrance is enriched with spices, aromatic herbs that leave soft and velvety effect which fills you with comfort and warm feelings of delightful Damascus rose.",
      "notes": [
        "atlantic cedarwood",
        "damask rose",
        "saffron"
      ],
      "ingredients": "saffron, damask rose, atlantic cedar"
    },
    {
      "id": "eg-070-marina-de-bourbon-monsieur-le-prince-intense",
      "name": "Marina De Bourbon Monsieur Le Prince Intense",
      "brand": "Marina De Bourbon",
      "gender": "Men",
      "family": "Fruity",
      "character": "Sophisticated",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2015,
      "priceSar": 322,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_marina_de_bourbon_perfumes_monsieur_le_prince_intense_for_men_eau_de_perfum_3494800610038.jpg",
      "description": "This Fruity fragrance inspired by the royal family that adds vitality and confidence in all your moves to enjoy your strong personality and attractive appearance.",
      "notes": [
        "amber",
        "apples",
        "bergamot",
        "jasmine",
        "musk",
        "pineapple",
        "sage",
        "skin",
        "white woods"
      ],
      "ingredients": "apple , pineapple , bergamot , leather , sage , jasmine , musk , amber , white woods."
    },
    {
      "id": "eg-071-dior-fahrenheit",
      "name": "Dior Fahrenheit",
      "brand": "Dior",
      "gender": "Men",
      "family": "Fruity",
      "character": "Masculine",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2003,
      "priceSar": 395,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/d/i/dior_fahrenheit_eau_de_toilette_2.jpg",
      "description": "For those who are looking for a bold, complex scent, there is Fahrenheit cologne for men. Created in 1988, this woody fragrance features citrus top notes of Sicilian mandarin and lemon...",
      "notes": [
        "amber",
        "bergamot",
        "carnation",
        "cedar",
        "chamomile",
        "hawthorn",
        "honeysuckle",
        "jasmine",
        "lavender",
        "leather",
        "lemon",
        "lily-of-the-valley",
        "mace",
        "mandarin"
      ],
      "ingredients": "bergamot, chamomile, lavender, mandarin, mace, hawthorn, cedar, lemon,carnation, honeysuckle, jasmine, lily-of-the-valley, nutmeg, sandalwood, violet leaf, cedar,amber, leather, musk, patchouli, tonka bean, vetiver"
    },
    {
      "id": "eg-072-nasomatto-pardon",
      "name": "Nasomatto Pardon",
      "brand": "Nasomatto",
      "gender": "Men",
      "family": "Woody",
      "character": "Romantic",
      "concentration": "Extrait de Parfum",
      "size": "30 ml",
      "year": 2011,
      "priceSar": 668,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_nasomatto_perfumes_pardon_for_men_extrait_de_parfum_perfume.jpg",
      "description": "A woody fragrance for men with a deep and strong masculine scent suitable for evening use, it changes negative feelings into positive ones to make you smile and feeling free to charm those...",
      "notes": [
        "chocolate",
        "cinnamon",
        "floral notes",
        "magnolia",
        "oud",
        "sandalwood",
        "tonka bean"
      ],
      "ingredients": "magnolia flower, floral, dark chocolate, tonka bean, cinnamon, agarwood, sandalwood."
    },
    {
      "id": "eg-073-jean-paul-gaultier-le-male",
      "name": "Jean Paul Gaultier Le Male",
      "brand": "Jean Paul Gaultier",
      "gender": "Men",
      "family": "Soft Oriental",
      "character": "Sensual",
      "concentration": "Eau de Toilette",
      "size": "125 ml",
      "year": 1995,
      "priceSar": 435,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_jean_paul_gaultier_perfumes_le_male_for_men_eau_de_toilette.jpg",
      "description": "A fragrant fragrance with a luxuriously masculine scent, which comes in a warm and distinctive formula that captivates your heart and keeps you attractive throughout the day. The fragrance...",
      "notes": [
        "and amber",
        "and bergamot",
        "and cumin",
        "artemesia",
        "cardamom",
        "cedar",
        "cinnamon",
        "lavender",
        "mint",
        "orange blossom",
        "sandalwood",
        "tonka bean",
        "vanilla"
      ],
      "ingredients": "artemisia, lavender, mint, bergamot, cardamom, caraway, orange blossom, cinnamon, sandalwood, tonka bean, amber, vanilla, cedar."
    },
    {
      "id": "eg-074-calvin-klein-man",
      "name": "Calvin Klein Man",
      "brand": "Calvin Klein",
      "gender": "Men",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2007,
      "priceSar": 146,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/calvin_klein_calvin_klein_man_edt_100_ml.jpg",
      "description": "A luxurious oriental woody fragrance for the modern, attractive and elegant man. This fragrance has a strong masculine scent full of luxury and sophistication that you will not be able to...",
      "notes": [
        "bay",
        "bergamot",
        "cypress",
        "guaiac and amberwood",
        "incense",
        "mandarin",
        "nutmeg",
        "rosemary",
        "sandalwood",
        "spearmint",
        "violet leaf"
      ],
      "ingredients": "nutmeg, mandarin, bergamot, violet leaf, rosemary, bay, spearmint, sandalwood, incense, cypress, guaiac and amberwood."
    },
    {
      "id": "eg-075-giorgio-armani-code-absolu",
      "name": "Giorgio Armani Code Absolu",
      "brand": "Giorgio Armani",
      "gender": "Women",
      "family": "Oriental",
      "character": "Classical",
      "concentration": "Eau de Parfum",
      "size": "110 ml",
      "year": 2019,
      "priceSar": 502,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/6/3614272407442_giorgio_armani_code_absolu_edp_110_ml_1.jpg",
      "description": "An oriental, addictive, spicy fragrance for men. It has the highest percentage of essential oils, as well as notes of tonka beans and vanilla, ensuring this scent will last all day and...",
      "notes": [
        "cardamom",
        "carrot seeds",
        "golden myrrh",
        "green mandarin",
        "nutmeg",
        "orange blossom",
        "tonka bean",
        "vanilla"
      ],
      "ingredients": "green mandarin, cardamom, orange blossom, nutmeg, carrot seeds, tonka bean, golden myrrh, vanilla"
    },
    {
      "id": "eg-076-carolina-herrera-212-sexy-men",
      "name": "Carolina Herrera 212 Sexy Men",
      "brand": "Carolina Herrera",
      "gender": "Men",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2006,
      "priceSar": 213,
      "rating": 5.0,
      "ratingCount": 2,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/carolina_herrera_vip_sexy_for_men.jpg",
      "description": "Oriental perfume for men gives you high attractiveness and excitement, with its elegant aroma, a mix of mandarin, cardamom, vanilla, musk, and amber. About the brand Carolina Herrera is a...",
      "notes": [
        "amber",
        "bergamot",
        "cardamom",
        "flowers",
        "green notes",
        "guaiac wood",
        "mandarin orange",
        "musk",
        "pepper",
        "sandalwood",
        "vanilla"
      ],
      "ingredients": "mandarin orange, bergamot, green notes, cardamom, flowers, pepper, vanilla, sandalwood, guaiac wood, musk, amber."
    },
    {
      "id": "eg-077-uniqo-tempesta-edp",
      "name": "Uniqo Tempesta EDP",
      "brand": "Uniqo",
      "gender": "Men",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2019,
      "priceSar": 110,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/u/n/uniqo-tempesta.png",
      "description": "A unique scent inspired by the magnetic force of Tempesta (Storm in Italian). This life-shifting power, chaotic yet undescribable with its' blend of marine accords, bay leaf & ambergris.",
      "notes": [
        "ambergris",
        "bay leaf",
        "marine accords"
      ],
      "ingredients": "marine accords, bay leaf, ambergris"
    },
    {
      "id": "eg-078-maqam-base-of-soul-edp",
      "name": "Maqam Base of Soul EDP",
      "brand": "Maqam",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "120 ml",
      "year": 2020,
      "priceSar": 319,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/maqam_base_of_soul-2.png",
      "description": "It takes only one encounter to fall in love with this oriental fragrance & reside in your memories forever! It has been composed as a sensual aroma, taking you on a profound journey into...",
      "notes": [
        "musk",
        "rose",
        "saffron",
        "sandalwod"
      ],
      "ingredients": "saffron, rose, musk, sandalwod"
    },
    {
      "id": "eg-079-very-important-notes-no-2-edp",
      "name": "Very Important Notes No 2 EDP",
      "brand": "Very Important Notes",
      "gender": "Unisex",
      "family": "Floral Oriental",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2020,
      "priceSar": 295,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/v/i/vin_2-ver2-3.jpg",
      "description": "For the Royal soul in you. This fragrance is the most profound scent from Very Important Notes collection. A true eastern masterpiece, merging amber, oud wood, Bulgarian rose & saffron to...",
      "notes": [
        "amber",
        "oud",
        "pepper",
        "rose",
        "saffron"
      ],
      "ingredients": "saffron, pepper ,rose ,oud, amber"
    },
    {
      "id": "eg-080-mont-blanc-emblem",
      "name": "Mont Blanc Emblem",
      "brand": "Mont Blanc",
      "gender": "Men",
      "family": "Woody Oriental",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "100 ml",
      "year": 2014,
      "priceSar": 144,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/3/3386460058735c-mont-blanc-emblem---100-ml.jpg",
      "description": "Emblem is Montblanc's latest masculine arrival embodies a unique authentic essence. A burst of clary sage and cardamom mixed with sparkling grapefruit immediately reveals a strong...",
      "notes": [
        "cardamom",
        "cinnamon",
        "clary sage",
        "frozen violet leaf",
        "grapefruit",
        "tonka bean",
        "woods"
      ],
      "ingredients": "grapefruit, sage, cardamom, violet leaf, cinnamon, wood, tonka bean"
    },
    {
      "id": "eg-081-the-finest-oud-edp",
      "name": "The Finest Oud EDP",
      "brand": "The Finest",
      "gender": "Unisex",
      "family": "Oriental",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 249,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/t/h/the-finest-oud.jpg",
      "description": "\"Warm, deep and rich\" A fragrant blend with endless creativity! Rich in its luxurious oriental Oud, deep thanks to its amber and musky notes, and warm with its woody notes, cashmere, and...",
      "notes": [
        "oudy notes",
        "pink pepper",
        "white musk"
      ],
      "ingredients": "pink pepper, oudy notes, white musk"
    },
    {
      "id": "eg-082-givenchy-eau-de-moiselle",
      "name": "Givenchy Eau De Moiselle",
      "brand": "Givenchy",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "50 ml",
      "year": 2008,
      "priceSar": 306,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/i/givenchy_eau_de_moiselle_eau_de_toilette_1.jpg",
      "description": "Create a vintage vibe around your outfit by wearing Eau Demoiselle perfume from Givenchy. This fragrance is wholly on its own. It is not quite modern but not quite traditional. It exists on...",
      "notes": [
        "ambrette (musk mallow)",
        "basil",
        "lemon",
        "musk",
        "rose",
        "tangerine",
        "tonka bean",
        "ylang-ylang"
      ],
      "ingredients": "lemon, tangerine, basil,ylang-ylang, rose,musk, tonka bean, ambrette (musk mallow)"
    },
    {
      "id": "eg-083-maqam-base-of-sight-edp",
      "name": "Maqam Base of Sight EDP",
      "brand": "Maqam",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "120 ml",
      "year": 2020,
      "priceSar": 319,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/m/a/maqam-sight-2.png",
      "description": "This perfume holds a distinctive identity, idolizing oriental charm, and creating a mesmerizing ether. It revives an inspirational feel, thanks to its extracted Arabian & natural notes...",
      "notes": [
        "coconut",
        "geranium",
        "vanilla",
        "woody notes"
      ],
      "ingredients": "geranium, coconut, woody notes, vanilla"
    },
    {
      "id": "eg-084-versace-eros-pour-homme",
      "name": "Versace Eros Pour Homme",
      "brand": "Versace",
      "gender": "Men",
      "family": "Woody Oriental",
      "character": "Sophisticated",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 299,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/8/0/8011003861224-versace-versace-eros-pour-homme-edp-100-ml.jpg",
      "description": "For the strong man who is the master of himself, this oriental woody fragrance is dedicated to you. The composition has notes of mint in the top, geranium in the middle, and vanilla in the...",
      "notes": [
        "ambroxan",
        "bitter orange",
        "candy apple",
        "cedar",
        "clary sage",
        "geranium",
        "leather",
        "lemon",
        "mandarin orange",
        "mint",
        "patchouli",
        "sandalwood",
        "vanilla"
      ],
      "ingredients": "mint, candy apple, lemon, mandarin orange, ambroxan, clary sage, geranium, vanilla, leather, sandalwood, bitter orange, cedar, patchouli"
    },
    {
      "id": "eg-085-orto-parisi-terroni",
      "name": "Orto Parisi Terroni",
      "brand": "Orto Parisi",
      "gender": "Women",
      "family": "Aromatic",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2017,
      "priceSar": 720,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/8/7/8717774840863-orto-parisi-orto-parisi-terroni-_u_-parfum-50-ml-1.jpg",
      "description": "The magic of nature is in harmony with the scents of cashmere and musk drops to caress your skin with an almost imperceptible force as the sun rays caress the earth and green rouge on it to...",
      "notes": [
        "cashmere wood",
        "cotton candy",
        "cypriol",
        "musk",
        "rice"
      ],
      "ingredients": "cashmere wood, cotton candy, cibriol, musk, cedar"
    },
    {
      "id": "eg-086-yves-saint-laurent-black-opium",
      "name": "Yves Saint Laurent Black Opium",
      "brand": "Yves Saint Laurent",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2017,
      "priceSar": 424,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/y/v/yves_saint_laurant_black_opium.jpg",
      "description": "Black Opium, the new fragrance announced as a rock'n'roll interpretation of the classic that should highlight the dark, mysterious side of the YSL brand. Master perfumers Nathalie Lorson...",
      "notes": [
        "almond",
        "cedar",
        "coffee",
        "jasmine",
        "patchouli",
        "pink pepper",
        "vanilla",
        "wood"
      ],
      "ingredients": "vanilla , patchouli , cedar , wood , coffee , jasmine , almond , pink pepper"
    },
    {
      "id": "eg-087-the-finest-amber-edp",
      "name": "The Finest Amber EDP",
      "brand": "The Finest",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 249,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/t/h/the-finest-amber.jpg",
      "description": "\u201cSweet, Strong and Spicy\" A fragrant blend with endless creativity! Sweet notes of amber and delicious vanilla, strong thanks to its woody notes from sandalwood to patchouli, and spicy from...",
      "notes": [
        "amber",
        "cardamom",
        "cedarwood",
        "vanilla"
      ],
      "ingredients": "cardamom, cedarwood, amber, vanilla"
    },
    {
      "id": "eg-088-lorenzo-villoresi-teint-de-neige-edp",
      "name": "Lorenzo Villoresi Teint De Neige EDP",
      "brand": "Lorenzo Villoresi Firenze",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2000,
      "priceSar": 790,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/g/o/golden_scent_perfume_lorenzo_villoresi_firenze_perfumes_teint_de_neige_eau_de_parfum.jpg",
      "description": "It's a delicate aromatic scent for both men and women that reminds of memories with its images, lights and atmosphere. Its rich extracts and precious notes of Ylang-Ylang, heliotrope and...",
      "notes": [
        "floral notes",
        "heliotrope",
        "jasmin",
        "musk",
        "powdery",
        "rose",
        "sweet",
        "tonka bean",
        "ylang ylang"
      ],
      "ingredients": "jasmin, ylang ylang, tonka bean, rose, heliotrope, musk, sweet, powdery, floral notes"
    },
    {
      "id": "eg-089-guerlain-musc-noble",
      "name": "Guerlain Musc Noble",
      "brand": "Guerlain",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "125 ml",
      "year": 2017,
      "priceSar": 567,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/3/3/3346470135079-guerlain-guerlain-musc-noble-_u_-edp-125-ml-1.jpg",
      "description": "A floral woody aromatic perfume was perfectly designed to suit men and women. It has an amazing long-lasting blend that's rich in sandalwood and geranium scents mixed in very fine...",
      "notes": [
        "aldehydes",
        "amber",
        "cedar wood",
        "geranium",
        "iris root",
        "labadenum",
        "leather",
        "musk",
        "pink pepper",
        "rose",
        "saffron"
      ],
      "ingredients": "aldehydes, pink pepper, saffron, geranium, musk, rose, iris root, leather, cedarwood, amber, labadenum, musk"
    },
    {
      "id": "eg-090-candy-addict-marshmallow-mash-edp",
      "name": "Candy Addict Marshmallow Mash EDP",
      "brand": "Candy Addict",
      "gender": "Women",
      "family": "Sweet",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2021,
      "priceSar": 139,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/ca-marshmallow-mash-edp-1.jpg",
      "description": "Description A deliciously nostalgic scent combination that will transport you to a land of funfairs and campfires with every spritz! The opening notes of juicy peach lead to the sweet...",
      "notes": [
        "marshmallow",
        "peach",
        "vanilla"
      ],
      "ingredients": "peach, marshmallow, vanilla"
    },
    {
      "id": "eg-091-candy-addict-musky-musk-edp",
      "name": "Candy Addict Musky Musk EDP",
      "brand": "Candy Addict",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2021,
      "priceSar": 139,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/ca-musky-musk-edp-1.jpg",
      "description": "Description Beautiful, earthy notes of musk are layered with bergamot and rose to create a musk perfume sensation! The combination of warm and floral notes makes a sensual, unforgettable...",
      "notes": [
        "bergamot",
        "musk",
        "rose"
      ],
      "ingredients": "bergamot, rose, musk"
    },
    {
      "id": "eg-092-candy-addict-powdery-pow-edp",
      "name": "Candy Addict Powdery Pow EDP",
      "brand": "Candy Addict",
      "gender": "Women",
      "family": "Floral Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2021,
      "priceSar": 139,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/c/a/ca-powdery-pow-edp-1.jpg",
      "description": "Want to be that person that smells so good you make everyone wonder what you're wearing? The fresh, dry sweetness of Powdery Pow will make you that person! The opening notes of rose & iris...",
      "notes": [
        "amber",
        "musk",
        "osmanthus"
      ],
      "ingredients": "osmanthus , musk , amber"
    },
    {
      "id": "eg-093-lacoste-eau-de-lacoste",
      "name": "Lacoste Eau De Lacoste",
      "brand": "Lacoste",
      "gender": "Women",
      "family": "Floral",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "50 ml",
      "year": 2017,
      "priceSar": 192,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/l/a/lacoste_eau_de_lacoste_eau_de_parfum_copy.jpg",
      "description": "The design of this feminine rich fragrance is inspired by the shape of the tennis ball to show universality and simplicity, which represent Lacoste's ideologies. The blend of pineapple...",
      "notes": [
        "bergamot",
        "mandarin",
        "orange blossom",
        "peru balsam",
        "pineapple",
        "pineapple blossom",
        "sambac jasmine",
        "sandalwood",
        "vanilla",
        "vetiver"
      ],
      "ingredients": "pineapple, mandarin, bergamot, sambac jasmine, orange blossom, pineapple blossom, sandalwood, peru balsam, vetiver, vanilla"
    },
    {
      "id": "eg-094-rekaz-patchouli",
      "name": "Rekaz Patchouli",
      "brand": "Rekaz",
      "gender": "Women",
      "family": "Oriental",
      "character": "Romantic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2017,
      "priceSar": 119,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/small_image/750x750/9df78eab33525d08d6e5fb8d27136e95/r/e/rekaz_patchouli_box_bottles.jpg",
      "description": "This bundle includes: Eau De Parfum 50 ml + Perfume Oil 30 ml / 2.57 Tola An irreplaceable component in the Arabian perfume world, created especially for the youthful empowered soul! This...",
      "notes": [
        "black pepper",
        "sulawesi patchouli",
        "ylang ylang"
      ],
      "ingredients": "black pepper, ylang ylang, sulawesi patchouli"
    },
    {
      "id": "eg-095-burberry-brit-rhythm-floral",
      "name": "Burberry Brit Rhythm Floral",
      "brand": "Burberry",
      "gender": "Women",
      "family": "Woody",
      "character": "Romantic",
      "concentration": "Eau de Toilette",
      "size": "90 ml",
      "year": 2017,
      "priceSar": 149,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/b/u/burberry_brit_rhythm_floral_for_woman.jpg",
      "description": "Burberry introduced the fragrant pair inspired by the British rock scene; Brit Rhythm for Him was launched first in September 2013., followed by the feminine edition Brit Rhythm for Her in...",
      "notes": [
        "jasmine",
        "musk",
        "wood"
      ],
      "ingredients": "jasmine, wood, musk"
    },
    {
      "id": "eg-096-tom-ford-black-orchid",
      "name": "Tom Ford Black Orchid",
      "brand": "Tom Ford",
      "gender": "Women",
      "family": "Woody",
      "character": "Charismatic",
      "concentration": "Eau de Parfum",
      "size": "100 ml",
      "year": 2006,
      "priceSar": 391,
      "rating": 5.0,
      "ratingCount": 1,
      "image": "https://assets.goldenscent.com/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/8/8/888066000062c-tom-ford-black-orchid---100-ml.jpg",
      "description": "It's a Natural Eau de Parfum that with a composition that begins with notes of Jasmine, Black Truffle, Ylang-ylang, Black Currant, Citrus, the heart notes of Black Orchid that represents...",
      "notes": [
        "amber",
        "balsam",
        "black currant",
        "black orchid",
        "black truffle",
        "citrus",
        "dark chocolate",
        "incense",
        "jasmine",
        "patchouli",
        "sandalwood",
        "vanilla",
        "vetiver",
        "ylang-ylang"
      ],
      "ingredients": "jasmine, black truffle, ylang-ylang, black currant, citrus, black orchid, patchouli, sandalwood, dark chocolate, incense, amber, vetiver, vanilla, balsam"
    }
  ]
};
